"""
This type stub file was generated by pyright.
"""

import io

class IterStream(io.RawIOBase):
    """Wraps an iterator yielding bytes as a file object"""
    def __init__(self, iterator) -> None:
        ...
    
    def readable(self): # -> Literal[True]:
        ...
    
    def writable(self) -> bool:
        ...
    
    def readinto(self, b):
        ...
    
    readinto1 = ...
    def read1(self, n=...):
        ...
    
    def peek(self, n): # -> bytes:
        ...
    


